# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['service.py', 'main.py', 'collector.py', 'executor.py'],  # 모든 소스 파일 명시
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'psutil',
        'psutil._pswindows',
        'psutil._psutil_windows',
        'wmi',
        'win32com',
        'win32com.client',
        'pythoncom',
        'pywintypes',
        'requests',
        'urllib3',
        'charset_normalizer',
        'idna',
        'certifi',
        'win32service',
        'win32serviceutil',
        'win32event',
        'servicemanager',
        'win32timezone',
        'win32api',
        'win32con',
        'win32file',
        'win32pipe',
        'win32process',
        'win32security',
        'ntsecuritycon',
        'commctrl',
        'winerror',
        'winreg'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='WCMS-Client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)
