# Generated by Django 5.2.15 on 2026-06-16 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rows', models.PositiveIntegerField(default=6)),
                ('cols', models.PositiveIntegerField(default=8)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', '등록됨'), ('revoked', '취소됨')], default='enrolled', max_length=16)),
                ('certificate_pem', models.TextField(blank=True, null=True)),
                ('legacy_machine_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_with_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='enrollment.enrollmenttoken')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='fleet.room')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDynamicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('ram_used', models.FloatField(help_text='GB')),
                ('ram_usage_percent', models.FloatField()),
                ('disk_usage', models.JSONField(blank=True, null=True)),
                ('current_user', models.CharField(blank=True, max_length=255, null=True)),
                ('uptime', models.PositiveIntegerField(help_text='초')),
                ('processes', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='fleet.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(max_length=255)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('cpu_threads', models.PositiveIntegerField()),
                ('ram_total', models.FloatField(help_text='GB')),
                ('disk_info', models.JSONField(default=dict)),
                ('os_edition', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='fleet.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('download_url', models.CharField(blank=True, max_length=512, null=True)),
                ('changelog', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
                'indexes': [models.Index(fields=['-released_at', '-id'], name='fleet_clien_release_8cb216_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='fleet.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.room')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_at', models.DateTimeField()),
                ('online_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(default='unknown', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_events', to='fleet.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', '-offline_at'], name='fleet_netwo_client__bc9df3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='fleet_clien_status_12d213_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_online', 'last_seen'], name='fleet_clien_is_onli_629236_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['room'], name='fleet_clien_room_id_b4f164_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['room'], name='fleet_seat_room_id_c2de14_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['client'], name='fleet_seat_client__35d25a_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'row', 'col'), name='uniq_seat_cell'),
        ),
    ]
