# Generated by Django 5.2.15 on 2026-06-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('detail', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('client_ts', models.DateTimeField(blank=True, help_text='클라이언트 측 발생 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='서버 수신 시각')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='fleet.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', '-created_at'], name='clientlogs__client__fd04a6_idx'), models.Index(fields=['level', '-created_at'], name='clientlogs__level_442a84_idx')],
            },
        ),
    ]
