# Generated by Django 5.2.15 on 2026-06-16 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('delivery_mode', models.CharField(choices=[('drop_if_offline', '오프라인 시 폐기'), ('queue', '큐잉(재연결 시 전달)')], default='queue', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '전달됨'), ('executing', '실행 중'), ('completed', '완료'), ('error', '에러'), ('timeout', '타임아웃'), ('expired', '만료')], default='pending', max_length=16)),
                ('result', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='fleet.client')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'status'], name='commands_co_client__443534_idx'), models.Index(fields=['status', 'priority', 'created_at'], name='commands_co_status_cf355e_idx'), models.Index(fields=['issuer', '-created_at'], name='commands_co_issuer__39b363_idx')],
            },
        ),
    ]
