# Generated by Django 5.2.15 on 2026-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('usage_type', models.CharField(choices=[('single', '1회용'), ('multi', '재사용')], default='single', max_length=8)),
                ('expires_in', models.PositiveIntegerField(default=600, help_text='초')),
                ('is_expired', models.BooleanField(default=False)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='enrollment__token_e9dd1a_idx'), models.Index(fields=['expires_at'], name='enrollment__expires_66aa42_idx')],
            },
        ),
    ]
